/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgreementRouteImport } from './routes/agreement'
import { Route as AiMatchRouteImport } from './routes/ai-match'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as PostRouteImport } from './routes/post'
import { Route as PropertyIdRouteImport } from './routes/property.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgreementRoute = AgreementRouteImport.update({
  id: '/agreement',
  path: '/agreement',
  getParentRoute: () => rootRouteImport,
} as any)
const AiMatchRoute = AiMatchRouteImport.update({
  id: '/ai-match',
  path: '/ai-match',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const PostRoute = PostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyIdRoute = PropertyIdRouteImport.update({
  id: '/property/$id',
  path: '/property/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agreement': typeof AgreementRoute
  '/ai-match': typeof AiMatchRoute
  '/browse': typeof BrowseRoute
  '/compare': typeof CompareRoute
  '/favorites': typeof FavoritesRoute
  '/post': typeof PostRoute
  '/property/$id': typeof PropertyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agreement': typeof AgreementRoute
  '/ai-match': typeof AiMatchRoute
  '/browse': typeof BrowseRoute
  '/compare': typeof CompareRoute
  '/favorites': typeof FavoritesRoute
  '/post': typeof PostRoute
  '/property/$id': typeof PropertyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agreement': typeof AgreementRoute
  '/ai-match': typeof AiMatchRoute
  '/browse': typeof BrowseRoute
  '/compare': typeof CompareRoute
  '/favorites': typeof FavoritesRoute
  '/post': typeof PostRoute
  '/property/$id': typeof PropertyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agreement'
    | '/ai-match'
    | '/browse'
    | '/compare'
    | '/favorites'
    | '/post'
    | '/property/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agreement'
    | '/ai-match'
    | '/browse'
    | '/compare'
    | '/favorites'
    | '/post'
    | '/property/$id'
  id:
    | '__root__'
    | '/'
    | '/agreement'
    | '/ai-match'
    | '/browse'
    | '/compare'
    | '/favorites'
    | '/post'
    | '/property/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgreementRoute: typeof AgreementRoute
  AiMatchRoute: typeof AiMatchRoute
  BrowseRoute: typeof BrowseRoute
  CompareRoute: typeof CompareRoute
  FavoritesRoute: typeof FavoritesRoute
  PostRoute: typeof PostRoute
  PropertyIdRoute: typeof PropertyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agreement': {
      id: '/agreement'
      path: '/agreement'
      fullPath: '/agreement'
      preLoaderRoute: typeof AgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-match': {
      id: '/ai-match'
      path: '/ai-match'
      fullPath: '/ai-match'
      preLoaderRoute: typeof AiMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/$id': {
      id: '/property/$id'
      path: '/property/$id'
      fullPath: '/property/$id'
      preLoaderRoute: typeof PropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgreementRoute: AgreementRoute,
  AiMatchRoute: AiMatchRoute,
  BrowseRoute: BrowseRoute,
  CompareRoute: CompareRoute,
  FavoritesRoute: FavoritesRoute,
  PostRoute: PostRoute,
  PropertyIdRoute: PropertyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
